services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: problem5
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/problem5?schema=public"
      PORT: 3000
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
        npx prisma db push --accept-data-loss &&
        npm start
      "

volumes:
  postgres_data:
